name: React.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # Ou spécifie une version précise

      - name: Installer les dépendances
        run: bun install

      - name: Linter le code
        run: bun run lint  # Adapte la commande si nécessaire

      - name: Construire l'application
        run: bun run build # Adapte la commande si nécessaire

      - name: Déployer sur GitHub Pages
        if: github.ref == 'refs/heads/main' # Déployer uniquement depuis la branche main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Afficher le contenu du répertoire courant
        run: ls -la
